version: 2
jobs:
  one:
    docker:
      - image: circleci/open jdk:8-jdk

    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: echo "A first hello"
      - run: mvn clean package
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
