version: 2
jobs:
  build:
    docker:
      - image: circleci
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sudo apt-get update && apt-get upgrage
      - run: sudo apt-get -y install maven
      - run: mvn clean package
