version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: apt-get update && apt-get upgrage
      - run: sudo apt-get -y install maven
      - run: mvn clean package
